USE ROLE ACCOUNTADMIN;
CREATE OR REPLACE NETWORK RULE PRO.APP.ALLOW_ALL_RULE
  TYPE = 'HOST_PORT'
  MODE = 'EGRESS'
  VALUE_LIST= ('0.0.0.0:443', '0.0.0.0:80');

USE ROLE ACCOUNTADMIN;
CREATE OR REPLACE EXTERNAL ACCESS INTEGRATION ALLOW_ALL_EAI
ALLOWED_NETWORK_RULES = (PRO.APP.ALLOW_ALL_RULE)
ENABLED = true;